#!/bin/bash

DIR=`dirname "$(readlink -f "$0")"`
#echo $DIR
export LD_LIBRARY_PATH=$DIR/lib 
#export QT_DEBUG_PLUGINS=1
unset QTDIR
unset QT_PLUGIN_PATH
echo $DIR/bin/qtmips_gui
ldd -r $DIR/bin/qtmips_gui
$DIR/bin/qtmips_gui
